### ISSUE TITLE
CodePath Submission with Extensions

### ISSUE THREAD

**Issue by chmod600** [akshaykhole/MakeList#1]
Hello!

This app is an extension of my initial submission:
https://github.com/akshaykhole/DoStuff/issues/1

I have added the extensions suggested by you as well as implemented a feature that solves a problems that I face personally. 

Most todo items allow you to organize your life. But sometimes your friends/roommates may want to remind you of certain errands like "Bring milk when coming home", "Pay bills, rent", etc.

Makelist provides you a simple way of doing that: Just text your friends with the task in a simple format and it will be added to their ToDo. The way this is done is, Makelist monitors incoming messages and if it detects a message formatted for Makelist, it parses it and creates a Task.

The list view displays if a certain task was assigned by yourself or by somebody else. It is similar to most project management tools but for day-to-day todos. I will be refining the app further but please consider this as an initial MVP.

Thanks!

/cc @codepathreview @codepath

**Comment by nesquena** [comment]
Great, thanks for the update and glad to see you got a number of optionals implemented! We will be determining final admittance into the program over the next 2 weeks. For those not admitted as participants, we will offer access to applicants as a remote observer cohort that has access to the materials and is able to work on the projects at their own pace. You will be hearing from us again soon, hope you've enjoyed working on this project so far!

**Comment by chmod600** [comment]
Closing in favor of https://github.com/akshaykhole/MakeList/issues/2 as my submission for the next batch.
